--- #YAML:1.0
name: SVN-SVNLook
version: 0.01
author: |-
  Salvatore E. ScottoDiLuzio <lt>sal.scotto@gmail.com<gt>
abstract: Module to aid in creating subversion hooks
license: perl
provides: {}
generated_by: Module::Build version 0.25
